trackInfo = {
    'items' : [
        {
            'album': {
                'album_type': 'ALBUM',
                'artists': [
                    {
                        'external_urls': {
                            'spotify': 'https://open.spotify.com/artist/2h93pZq0e7k5yf4dywlkpM'
                        },
                        'href': 'https://api.spotify.com/v1/artists/2h93pZq0e7k5yf4dywlkpM',
                        'id': '2h93pZq0e7k5yf4dywlkpM',
                        'name': 'Frank Ocean',
                        'type': 'artist',
                        'uri': 'spotify:artist:2h93pZq0e7k5yf4dywlkpM'
                    }
                ],
                'available_markets': [
                    'AD',
                    'AE',
                    'AR',
                    'AT',
                    'AU',
                    'BE',
                    'BG',
                    'BH',
                    'BO',
                    'BR',
                    'CA',
                    'CH',
                    'CL',
                    'CO',
                    'CR',
                    'CY',
                    'CZ',
                    'DE',
                    'DK',
                    'DO',
                    'DZ',
                    'EC',
                    'EE',
                    'EG',
                    'ES',
                    'FI',
                    'FR',
                    'GB',
                    'GR',
                    'GT',
                    'HK',
                    'HN',
                    'HU',
                    'ID',
                    'IE',
                    'IL',
                    'IN',
                    'IS',
                    'IT',
                    'JO',
                    'JP',
                    'KW',
                    'LB',
                    'LI',
                    'LT',
                    'LU',
                    'LV',
                    'MA',
                    'MC',
                    'MT',
                    'MX',
                    'MY',
                    'NI',
                    'NL',
                    'NO',
                    'NZ',
                    'OM',
                    'PA',
                    'PE',
                    'PH',
                    'PL',
                    'PS',
                    'PT',
                    'PY',
                    'QA',
                    'RO',
                    'SA',
                    'SE',
                    'SG',
                    'SK',
                    'SV',
                    'TH',
                    'TN',
                    'TR',
                    'TW',
                    'US',
                    'UY',
                    'VN',
                    'ZA'
                ],
                'external_urls': {
                    'spotify': 'https://open.spotify.com/album/392p3shh2jkxUxY2VHvlH8'
                },
                'href': 'https://api.spotify.com/v1/albums/392p3shh2jkxUxY2VHvlH8',
                'id': '392p3shh2jkxUxY2VHvlH8',
                'images': [
                    {
                        'height': 640,
                        'url': 'https://i.scdn.co/image/ab67616d0000b2737aede4855f6d0d738012e2e5',
                        'width': 640
                    },
                    {
                        'height': 300,
                        'url': 'https://i.scdn.co/image/ab67616d00001e027aede4855f6d0d738012e2e5',
                        'width': 300
                    },
                    {
                        'height': 64,
                        'url': 'https://i.scdn.co/image/ab67616d000048517aede4855f6d0d738012e2e5',
                        'width': 64
                    }
                ],
                'name': 'channel ORANGE',
                'release_date': '2012-07-10',
                'release_date_precision': 'day',
                'total_tracks': 17,
                'type': 'album',
                'uri': 'spotify:album:392p3shh2jkxUxY2VHvlH8'
            },
            'artists': [
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/2h93pZq0e7k5yf4dywlkpM'
                    },
                    'href': 'https://api.spotify.com/v1/artists/2h93pZq0e7k5yf4dywlkpM',
                    'id': '2h93pZq0e7k5yf4dywlkpM',
                    'name': 'Frank Ocean',
                    'type': 'artist',
                    'uri': 'spotify:artist:2h93pZq0e7k5yf4dywlkpM'
                },
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/74V3dE1a51skRkdII8y2C6'
                    },
                    'href': 'https://api.spotify.com/v1/artists/74V3dE1a51skRkdII8y2C6',
                    'id': '74V3dE1a51skRkdII8y2C6',
                    'name': 'André 3000',
                    'type': 'artist',
                    'uri': 'spotify:artist:74V3dE1a51skRkdII8y2C6'
                }
            ],
            'available_markets': [
                'AD',
                'AE',
                'AR',
                'AT',
                'AU',
                'BE',
                'BG',
                'BH',
                'BO',
                'BR',
                'CA',
                'CH',
                'CL',
                'CO',
                'CR',
                'CY',
                'CZ',
                'DE',
                'DK',
                'DO',
                'DZ',
                'EC',
                'EE',
                'EG',
                'ES',
                'FI',
                'FR',
                'GB',
                'GR',
                'GT',
                'HK',
                'HN',
                'HU',
                'ID',
                'IE',
                'IL',
                'IN',
                'IS',
                'IT',
                'JO',
                'JP',
                'KW',
                'LB',
                'LI',
                'LT',
                'LU',
                'LV',
                'MA',
                'MC',
                'MT',
                'MX',
                'MY',
                'NI',
                'NL',
                'NO',
                'NZ',
                'OM',
                'PA',
                'PE',
                'PH',
                'PL',
                'PS',
                'PT',
                'PY',
                'QA',
                'RO',
                'SA',
                'SE',
                'SG',
                'SK',
                'SV',
                'TH',
                'TN',
                'TR',
                'TW',
                'US',
                'UY',
                'VN',
                'ZA'
            ],
            'disc_number': 1,
            'duration_ms': 268813,
            'explicit': true,
            'external_ids': {
                'isrc': 'USUM71207190'
            },
            'external_urls': {
                'spotify': 'https://open.spotify.com/track/1fOkmYW3ZFkkjIdOZSf596'
            },
            'href': 'https://api.spotify.com/v1/tracks/1fOkmYW3ZFkkjIdOZSf596',
            'id': '1fOkmYW3ZFkkjIdOZSf596',
            'is_local': false,
            'name': 'Pink Matter',
            'popularity': 75,
            'preview_url': null,
            'track_number': 15,
            'type': 'track',
            'uri': 'spotify:track:1fOkmYW3ZFkkjIdOZSf596'
        },
        {
            'album': {
                'album_type': 'ALBUM',
                'artists': [
                    {
                        'external_urls': {
                            'spotify': 'https://open.spotify.com/artist/3MZsBdqDrRTJihTHQrO6Dq'
                        },
                        'href': 'https://api.spotify.com/v1/artists/3MZsBdqDrRTJihTHQrO6Dq',
                        'id': '3MZsBdqDrRTJihTHQrO6Dq',
                        'name': 'Joji',
                        'type': 'artist',
                        'uri': 'spotify:artist:3MZsBdqDrRTJihTHQrO6Dq'
                    }
                ],
                'available_markets': [
                    'AD',
                    'AE',
                    'AR',
                    'AT',
                    'AU',
                    'BE',
                    'BG',
                    'BH',
                    'BO',
                    'BR',
                    'CA',
                    'CH',
                    'CL',
                    'CO',
                    'CR',
                    'CY',
                    'CZ',
                    'DE',
                    'DK',
                    'DO',
                    'DZ',
                    'EC',
                    'EE',
                    'EG',
                    'ES',
                    'FI',
                    'FR',
                    'GB',
                    'GR',
                    'GT',
                    'HK',
                    'HN',
                    'HU',
                    'ID',
                    'IE',
                    'IL',
                    'IN',
                    'IS',
                    'IT',
                    'JO',
                    'JP',
                    'KW',
                    'LB',
                    'LI',
                    'LT',
                    'LU',
                    'LV',
                    'MA',
                    'MC',
                    'MT',
                    'MX',
                    'MY',
                    'NI',
                    'NL',
                    'NO',
                    'NZ',
                    'OM',
                    'PA',
                    'PE',
                    'PH',
                    'PL',
                    'PS',
                    'PT',
                    'PY',
                    'QA',
                    'RO',
                    'SA',
                    'SE',
                    'SG',
                    'SK',
                    'SV',
                    'TH',
                    'TN',
                    'TR',
                    'TW',
                    'US',
                    'UY',
                    'VN',
                    'ZA'
                ],
                'external_urls': {
                    'spotify': 'https://open.spotify.com/album/34GQP3dILpyCN018y2k61L'
                },
                'href': 'https://api.spotify.com/v1/albums/34GQP3dILpyCN018y2k61L',
                'id': '34GQP3dILpyCN018y2k61L',
                'images': [
                    {
                        'height': 640,
                        'url': 'https://i.scdn.co/image/ab67616d0000b27360ba1d6104d0475c7555a6b2',
                        'width': 640
                    },
                    {
                        'height': 300,
                        'url': 'https://i.scdn.co/image/ab67616d00001e0260ba1d6104d0475c7555a6b2',
                        'width': 300
                    },
                    {
                        'height': 64,
                        'url': 'https://i.scdn.co/image/ab67616d0000485160ba1d6104d0475c7555a6b2',
                        'width': 64
                    }
                ],
                'name': 'BALLADS 1',
                'release_date': '2018-10-26',
                'release_date_precision': 'day',
                'total_tracks': 12,
                'type': 'album',
                'uri': 'spotify:album:34GQP3dILpyCN018y2k61L'
            },
            'artists': [
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/3MZsBdqDrRTJihTHQrO6Dq'
                    },
                    'href': 'https://api.spotify.com/v1/artists/3MZsBdqDrRTJihTHQrO6Dq',
                    'id': '3MZsBdqDrRTJihTHQrO6Dq',
                    'name': 'Joji',
                    'type': 'artist',
                    'uri': 'spotify:artist:3MZsBdqDrRTJihTHQrO6Dq'
                }
            ],
            'available_markets': [
                'AD',
                'AE',
                'AR',
                'AT',
                'AU',
                'BE',
                'BG',
                'BH',
                'BO',
                'BR',
                'CA',
                'CH',
                'CL',
                'CO',
                'CR',
                'CY',
                'CZ',
                'DE',
                'DK',
                'DO',
                'DZ',
                'EC',
                'EE',
                'EG',
                'ES',
                'FI',
                'FR',
                'GB',
                'GR',
                'GT',
                'HK',
                'HN',
                'HU',
                'ID',
                'IE',
                'IL',
                'IN',
                'IS',
                'IT',
                'JO',
                'JP',
                'KW',
                'LB',
                'LI',
                'LT',
                'LU',
                'LV',
                'MA',
                'MC',
                'MT',
                'MX',
                'MY',
                'NI',
                'NL',
                'NO',
                'NZ',
                'OM',
                'PA',
                'PE',
                'PH',
                'PL',
                'PS',
                'PT',
                'PY',
                'QA',
                'RO',
                'SA',
                'SE',
                'SG',
                'SK',
                'SV',
                'TH',
                'TN',
                'TR',
                'TW',
                'US',
                'UY',
                'VN',
                'ZA'
            ],
            'disc_number': 1,
            'duration_ms': 209273,
            'explicit': true,
            'external_ids': {
                'isrc': 'ZZOPM1800452'
            },
            'external_urls': {
                'spotify': 'https://open.spotify.com/track/0rKtyWc8bvkriBthvHKY8d'
            },
            'href': 'https://api.spotify.com/v1/tracks/0rKtyWc8bvkriBthvHKY8d',
            'id': '0rKtyWc8bvkriBthvHKY8d',
            'is_local': false,
            'name': 'SLOW DANCING IN THE DARK',
            'popularity': 85,
            'preview_url': 'https://p.scdn.co/mp3-preview/1aa59cfc4e15a45403fd35eb72ce62acd8a45f58?cid=00ae7f371a9646edadddca6020662144',
            'track_number': 2,
            'type': 'track',
            'uri': 'spotify:track:0rKtyWc8bvkriBthvHKY8d'
        },
        {
            'album': {
                'album_type': 'ALBUM',
                'artists': [
                    {
                        'external_urls': {
                            'spotify': 'https://open.spotify.com/artist/3tlXnStJ1fFhdScmQeLpuG'
                        },
                        'href': 'https://api.spotify.com/v1/artists/3tlXnStJ1fFhdScmQeLpuG',
                        'id': '3tlXnStJ1fFhdScmQeLpuG',
                        'name': 'Brent Faiyaz',
                        'type': 'artist',
                        'uri': 'spotify:artist:3tlXnStJ1fFhdScmQeLpuG'
                    }
                ],
                'available_markets': [
                    'AD',
                    'AE',
                    'AR',
                    'AT',
                    'AU',
                    'BE',
                    'BG',
                    'BH',
                    'BO',
                    'BR',
                    'CA',
                    'CH',
                    'CL',
                    'CO',
                    'CR',
                    'CY',
                    'CZ',
                    'DE',
                    'DK',
                    'DO',
                    'DZ',
                    'EC',
                    'EE',
                    'EG',
                    'ES',
                    'FI',
                    'FR',
                    'GB',
                    'GR',
                    'GT',
                    'HK',
                    'HN',
                    'HU',
                    'ID',
                    'IE',
                    'IL',
                    'IN',
                    'IS',
                    'IT',
                    'JO',
                    'JP',
                    'KW',
                    'LB',
                    'LI',
                    'LT',
                    'LU',
                    'LV',
                    'MA',
                    'MC',
                    'MT',
                    'MX',
                    'MY',
                    'NI',
                    'NL',
                    'NO',
                    'NZ',
                    'OM',
                    'PA',
                    'PE',
                    'PH',
                    'PL',
                    'PS',
                    'PT',
                    'PY',
                    'QA',
                    'RO',
                    'SA',
                    'SE',
                    'SG',
                    'SK',
                    'SV',
                    'TH',
                    'TN',
                    'TR',
                    'TW',
                    'US',
                    'UY',
                    'VN',
                    'ZA'
                ],
                'external_urls': {
                    'spotify': 'https://open.spotify.com/album/0PHMNbcgHfzSUALlfk7wGg'
                },
                'href': 'https://api.spotify.com/v1/albums/0PHMNbcgHfzSUALlfk7wGg',
                'id': '0PHMNbcgHfzSUALlfk7wGg',
                'images': [
                    {
                        'height': 640,
                        'url': 'https://i.scdn.co/image/ab67616d0000b27353aa764ce919d8aea07947b4',
                        'width': 640
                    },
                    {
                        'height': 300,
                        'url': 'https://i.scdn.co/image/ab67616d00001e0253aa764ce919d8aea07947b4',
                        'width': 300
                    },
                    {
                        'height': 64,
                        'url': 'https://i.scdn.co/image/ab67616d0000485153aa764ce919d8aea07947b4',
                        'width': 64
                    }
                ],
                'name': 'WASTELAND',
                'release_date': '2022-07-08',
                'release_date_precision': 'day',
                'total_tracks': 19,
                'type': 'album',
                'uri': 'spotify:album:0PHMNbcgHfzSUALlfk7wGg'
            },
            'artists': [
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/3tlXnStJ1fFhdScmQeLpuG'
                    },
                    'href': 'https://api.spotify.com/v1/artists/3tlXnStJ1fFhdScmQeLpuG',
                    'id': '3tlXnStJ1fFhdScmQeLpuG',
                    'name': 'Brent Faiyaz',
                    'type': 'artist',
                    'uri': 'spotify:artist:3tlXnStJ1fFhdScmQeLpuG'
                },
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/5BozIJTTNCufaZpjhy2der'
                    },
                    'href': 'https://api.spotify.com/v1/artists/5BozIJTTNCufaZpjhy2der',
                    'id': '5BozIJTTNCufaZpjhy2der',
                    'name': 'DJ Dahi',
                    'type': 'artist',
                    'uri': 'spotify:artist:5BozIJTTNCufaZpjhy2der'
                },
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF'
                    },
                    'href': 'https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF',
                    'id': '4V8LLVI7PbaPR0K2TGSxFF',
                    'name': 'Tyler, The Creator',
                    'type': 'artist',
                    'uri': 'spotify:artist:4V8LLVI7PbaPR0K2TGSxFF'
                }
            ],
            'available_markets': [
                'AD',
                'AE',
                'AR',
                'AT',
                'AU',
                'BE',
                'BG',
                'BH',
                'BO',
                'BR',
                'CA',
                'CH',
                'CL',
                'CO',
                'CR',
                'CY',
                'CZ',
                'DE',
                'DK',
                'DO',
                'DZ',
                'EC',
                'EE',
                'EG',
                'ES',
                'FI',
                'FR',
                'GB',
                'GR',
                'GT',
                'HK',
                'HN',
                'HU',
                'ID',
                'IE',
                'IL',
                'IN',
                'IS',
                'IT',
                'JO',
                'JP',
                'KW',
                'LB',
                'LI',
                'LT',
                'LU',
                'LV',
                'MA',
                'MC',
                'MT',
                'MX',
                'MY',
                'NI',
                'NL',
                'NO',
                'NZ',
                'OM',
                'PA',
                'PE',
                'PH',
                'PL',
                'PS',
                'PT',
                'PY',
                'QA',
                'RO',
                'SA',
                'SE',
                'SG',
                'SK',
                'SV',
                'TH',
                'TN',
                'TR',
                'TW',
                'US',
                'UY',
                'VN',
                'ZA'
            ],
            'disc_number': 1,
            'duration_ms': 214692,
            'explicit': true,
            'external_ids': {
                'isrc': 'QM24S2100085'
            },
            'external_urls': {
                'spotify': 'https://open.spotify.com/track/3zakx7RAwdkUQlOoQ7SJRt'
            },
            'href': 'https://api.spotify.com/v1/tracks/3zakx7RAwdkUQlOoQ7SJRt',
            'id': '3zakx7RAwdkUQlOoQ7SJRt',
            'is_local': false,
            'name': 'GRAVITY (FEAT. TYLER, THE CREATOR)',
            'popularity': 76,
            'preview_url': 'https://p.scdn.co/mp3-preview/8bd6efcd03b94dc7ffce29bc7d5187c583bb756f?cid=00ae7f371a9646edadddca6020662144',
            'track_number': 3,
            'type': 'track',
            'uri': 'spotify:track:3zakx7RAwdkUQlOoQ7SJRt'
        },
        {
            'album': {
                'album_type': 'ALBUM',
                'artists': [
                    {
                        'external_urls': {
                            'spotify': 'https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF'
                        },
                        'href': 'https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF',
                        'id': '4V8LLVI7PbaPR0K2TGSxFF',
                        'name': 'Tyler, The Creator',
                        'type': 'artist',
                        'uri': 'spotify:artist:4V8LLVI7PbaPR0K2TGSxFF'
                    }
                ],
                'available_markets': [
                    'AD',
                    'AE',
                    'AR',
                    'AT',
                    'AU',
                    'BE',
                    'BG',
                    'BH',
                    'BO',
                    'BR',
                    'CA',
                    'CH',
                    'CL',
                    'CO',
                    'CR',
                    'CY',
                    'CZ',
                    'DE',
                    'DK',
                    'DO',
                    'DZ',
                    'EC',
                    'EE',
                    'EG',
                    'ES',
                    'FI',
                    'FR',
                    'GB',
                    'GR',
                    'GT',
                    'HK',
                    'HN',
                    'HU',
                    'ID',
                    'IE',
                    'IL',
                    'IN',
                    'IS',
                    'IT',
                    'JO',
                    'JP',
                    'KW',
                    'LB',
                    'LI',
                    'LT',
                    'LU',
                    'LV',
                    'MA',
                    'MC',
                    'MT',
                    'MX',
                    'MY',
                    'NI',
                    'NL',
                    'NO',
                    'NZ',
                    'OM',
                    'PA',
                    'PE',
                    'PH',
                    'PL',
                    'PS',
                    'PT',
                    'PY',
                    'QA',
                    'RO',
                    'SA',
                    'SE',
                    'SG',
                    'SK',
                    'SV',
                    'TH',
                    'TN',
                    'TR',
                    'TW',
                    'US',
                    'UY',
                    'VN',
                    'ZA'
                ],
                'external_urls': {
                    'spotify': 'https://open.spotify.com/album/5zi7WsKlIiUXv09tbGLKsE'
                },
                'href': 'https://api.spotify.com/v1/albums/5zi7WsKlIiUXv09tbGLKsE',
                'id': '5zi7WsKlIiUXv09tbGLKsE',
                'images': [
                    {
                        'height': 640,
                        'url': 'https://i.scdn.co/image/ab67616d0000b2737005885df706891a3c182a57',
                        'width': 640
                    },
                    {
                        'height': 300,
                        'url': 'https://i.scdn.co/image/ab67616d00001e027005885df706891a3c182a57',
                        'width': 300
                    },
                    {
                        'height': 64,
                        'url': 'https://i.scdn.co/image/ab67616d000048517005885df706891a3c182a57',
                        'width': 64
                    }
                ],
                'name': 'IGOR',
                'release_date': '2019-05-17',
                'release_date_precision': 'day',
                'total_tracks': 12,
                'type': 'album',
                'uri': 'spotify:album:5zi7WsKlIiUXv09tbGLKsE'
            },
            'artists': [
                {
                    'external_urls': {
                        'spotify': 'https://open.spotify.com/artist/4V8LLVI7PbaPR0K2TGSxFF'
                    },
                    'href': 'https://api.spotify.com/v1/artists/4V8LLVI7PbaPR0K2TGSxFF',
                    'id': '4V8LLVI7PbaPR0K2TGSxFF',
                    'name': 'Tyler, The Creator',
                    'type': 'artist',
                    'uri': 'spotify:artist:4V8LLVI7PbaPR0K2TGSxFF'
                }
            ],
            'available_markets': [
                'AD',
                'AE',
                'AR',
                'AT',
                'AU',
                'BE',
                'BG',
                'BH',
                'BO',
                'BR',
                'CA',
                'CH',
                'CL',
                'CO',
                'CR',
                'CY',
                'CZ',
                'DE',
                'DK',
                'DO',
                'DZ',
                'EC',
                'EE',
                'EG',
                'ES',
                'FI',
                'FR',
                'GB',
                'GR',
                'GT',
                'HK',
                'HN',
                'HU',
                'ID',
                'IE',
                'IL',
                'IN',
                'IS',
                'IT',
                'JO',
                'JP',
                'KW',
                'LB',
                'LI',
                'LT',
                'LU',
                'LV',
                'MA',
                'MC',
                'MT',
                'MX',
                'MY',
                'NI',
                'NL',
                'NO',
                'NZ',
                'OM',
                'PA',
                'PE',
                'PH',
                'PL',
                'PS',
                'PT',
                'PY',
                'QA',
                'RO',
                'SA',
                'SE',
                'SG',
                'SK',
                'SV',
                'TH',
                'TN',
                'TR',
                'TW',
                'US',
                'UY',
                'VN',
                'ZA'
            ],
            'disc_number': 1,
            'duration_ms': 190066,
            'explicit': true,
            'external_ids': {
                'isrc': 'USQX91901111'
            },
            'external_urls': {
                'spotify': 'https://open.spotify.com/track/5hVghJ4KaYES3BFUATCYn0'
            },
            'href': 'https://api.spotify.com/v1/tracks/5hVghJ4KaYES3BFUATCYn0',
            'id': '5hVghJ4KaYES3BFUATCYn0',
            'is_local': false,
            'name': 'EARFQUAKE',
            'popularity': 84,
            'preview_url': 'https://p.scdn.co/mp3-preview/d12bb695962e3e21ad6f737898de806ad970671a?cid=00ae7f371a9646edadddca6020662144',
            'track_number': 2,
            'type': 'track',
            'uri': 'spotify:track:5hVghJ4KaYES3BFUATCYn0'
        }
    ]
}

// let obj = JSON.parse(trackInfo)
